package com.huaao.sunejwapi.mapper;

import com.huaao.sunejwapi.dao.JwUser;
import com.huaao.sunejwapi.dao.JwUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JwUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_user
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int countByExample(JwUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_user
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int deleteByExample(JwUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_user
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_user
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int insert(JwUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_user
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int insertSelective(JwUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_user
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    List<JwUser> selectByExampleWithBLOBs(JwUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_user
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    List<JwUser> selectByExample(JwUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_user
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    JwUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_user
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int updateByExampleSelective(@Param("record") JwUser record, @Param("example") JwUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_user
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") JwUser record, @Param("example") JwUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_user
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int updateByExample(@Param("record") JwUser record, @Param("example") JwUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_user
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int updateByPrimaryKeySelective(JwUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_user
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(JwUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jw_user
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int updateByPrimaryKey(JwUser record);
}