package com.huaao.sunejwapi.mapper;

import com.huaao.sunejwapi.dao.SpsResidence;
import com.huaao.sunejwapi.dao.SpsResidenceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpsResidenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sps_residence
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int countByExample(SpsResidenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sps_residence
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int deleteByExample(SpsResidenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sps_residence
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sps_residence
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int insert(SpsResidence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sps_residence
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int insertSelective(SpsResidence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sps_residence
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    List<SpsResidence> selectByExample(SpsResidenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sps_residence
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    SpsResidence selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sps_residence
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int updateByExampleSelective(@Param("record") SpsResidence record, @Param("example") SpsResidenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sps_residence
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int updateByExample(@Param("record") SpsResidence record, @Param("example") SpsResidenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sps_residence
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int updateByPrimaryKeySelective(SpsResidence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sps_residence
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    int updateByPrimaryKey(SpsResidence record);
}