package com.huaao.sunejwapi.dao;

import java.io.Serializable;

public class SpsSDictionary implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sps_s_dictionary.id
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sps_s_dictionary.communityid
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    private Integer communityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sps_s_dictionary.dictionary_img
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    private String dictionaryImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sps_s_dictionary.dictionary_name
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    private String dictionaryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sps_s_dictionary.dictionary_code
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    private String dictionaryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sps_s_dictionary.dictionary_parent_id
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    private Integer dictionaryParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sps_s_dictionary.dictionary_order
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    private Integer dictionaryOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sps_s_dictionary.dictionary_value
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    private String dictionaryValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sps_s_dictionary.status
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sps_s_dictionary.createtime
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    private Long createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sps_s_dictionary.updatetime
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    private Long updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sps_s_dictionary.uid
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sps_s_dictionary
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sps_s_dictionary.id
     *
     * @return the value of sps_s_dictionary.id
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sps_s_dictionary.id
     *
     * @param id the value for sps_s_dictionary.id
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sps_s_dictionary.communityid
     *
     * @return the value of sps_s_dictionary.communityid
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public Integer getCommunityid() {
        return communityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sps_s_dictionary.communityid
     *
     * @param communityid the value for sps_s_dictionary.communityid
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public void setCommunityid(Integer communityid) {
        this.communityid = communityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sps_s_dictionary.dictionary_img
     *
     * @return the value of sps_s_dictionary.dictionary_img
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public String getDictionaryImg() {
        return dictionaryImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sps_s_dictionary.dictionary_img
     *
     * @param dictionaryImg the value for sps_s_dictionary.dictionary_img
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public void setDictionaryImg(String dictionaryImg) {
        this.dictionaryImg = dictionaryImg == null ? null : dictionaryImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sps_s_dictionary.dictionary_name
     *
     * @return the value of sps_s_dictionary.dictionary_name
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public String getDictionaryName() {
        return dictionaryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sps_s_dictionary.dictionary_name
     *
     * @param dictionaryName the value for sps_s_dictionary.dictionary_name
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public void setDictionaryName(String dictionaryName) {
        this.dictionaryName = dictionaryName == null ? null : dictionaryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sps_s_dictionary.dictionary_code
     *
     * @return the value of sps_s_dictionary.dictionary_code
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public String getDictionaryCode() {
        return dictionaryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sps_s_dictionary.dictionary_code
     *
     * @param dictionaryCode the value for sps_s_dictionary.dictionary_code
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public void setDictionaryCode(String dictionaryCode) {
        this.dictionaryCode = dictionaryCode == null ? null : dictionaryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sps_s_dictionary.dictionary_parent_id
     *
     * @return the value of sps_s_dictionary.dictionary_parent_id
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public Integer getDictionaryParentId() {
        return dictionaryParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sps_s_dictionary.dictionary_parent_id
     *
     * @param dictionaryParentId the value for sps_s_dictionary.dictionary_parent_id
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public void setDictionaryParentId(Integer dictionaryParentId) {
        this.dictionaryParentId = dictionaryParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sps_s_dictionary.dictionary_order
     *
     * @return the value of sps_s_dictionary.dictionary_order
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public Integer getDictionaryOrder() {
        return dictionaryOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sps_s_dictionary.dictionary_order
     *
     * @param dictionaryOrder the value for sps_s_dictionary.dictionary_order
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public void setDictionaryOrder(Integer dictionaryOrder) {
        this.dictionaryOrder = dictionaryOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sps_s_dictionary.dictionary_value
     *
     * @return the value of sps_s_dictionary.dictionary_value
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public String getDictionaryValue() {
        return dictionaryValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sps_s_dictionary.dictionary_value
     *
     * @param dictionaryValue the value for sps_s_dictionary.dictionary_value
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public void setDictionaryValue(String dictionaryValue) {
        this.dictionaryValue = dictionaryValue == null ? null : dictionaryValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sps_s_dictionary.status
     *
     * @return the value of sps_s_dictionary.status
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sps_s_dictionary.status
     *
     * @param status the value for sps_s_dictionary.status
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sps_s_dictionary.createtime
     *
     * @return the value of sps_s_dictionary.createtime
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sps_s_dictionary.createtime
     *
     * @param createtime the value for sps_s_dictionary.createtime
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sps_s_dictionary.updatetime
     *
     * @return the value of sps_s_dictionary.updatetime
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public Long getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sps_s_dictionary.updatetime
     *
     * @param updatetime the value for sps_s_dictionary.updatetime
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public void setUpdatetime(Long updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sps_s_dictionary.uid
     *
     * @return the value of sps_s_dictionary.uid
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sps_s_dictionary.uid
     *
     * @param uid the value for sps_s_dictionary.uid
     *
     * @mbggenerated Sat May 27 10:52:47 CST 2017
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}